### ISSUE TITLE
Error: Json error in default.json plugin config file

### ISSUE THREAD

**Issue by lvs2020** [pjjonesnz/directadmin_cloudflare_dns#3]
Plugin working fine but when edit default.json to true with proxy enable on some records there is error as below:
Cloudflare domain added without proxy enable while domain not created in Directadmin:

Could not write domain's db file in /var/named
Script output: /usr/local/directadmin/scripts/custom/dns_write_post.sh
Error: Json error in default.json plugin config file.
User added to named.conf file successfully
Error Creating Domain

**Comment by pjjonesnz** [comment]
The part of that error that the plug-in is throwing is, "Error: Json error in default.json plugin config file."

When the json file is decoded by php it will throw that error if the json is invalid. 

I've just realised that the json in my examples in the readme actually doesn't validate. I'm more accustomed to writing 'json' when creating objects in JavaScript, which is much more forgiving than true json which needs double quotes around all keys and string values as well as no trailing commas (which was my error in the readme). Sorry if that caused your error.

Try pasting your file into the json validator to see where the error is.

https://jsonlint.com/

Hope that helps. I'm off to fix my readme...

**Comment by lvs2020** [comment]
Thanks for your kind support ! the problem fixed as per your instructions.
Excellent work !!!

**Comment by pjjonesnz** [comment]
Yay. Pleased that fixed it. Thanks for letting me know about the problem.
