### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by lvs2020** [pjjonesnz/directadmin_cloudflare_dns#4]
What is easy way to update the version ?

**Comment by pjjonesnz** [comment]
Sadly there is no super easy way at this stage.

This is what I do, basically going through the install sequence, but copying my settings over to the new install

1. ssh to the server in my home folder (ie. /home/admin) and rename (or remove) any old version that is sitting in my /home/admin folder (```mv directadmin_cloudflare_dns old_directadmin_cloudflare_dns```)
2. ```git clone https://github.com/pjjonesnz/directadmin_cloudflare_dns.git```
3. ```cd directadmin_cloudflare_dns/da_cloudflare_dns_sync```
4. run ```composer install``` (requires you to have composer installed on your system - if you don't then see [https://getcomposer.org/download/](https://getcomposer.org/download/) - follow the Command-line installation)
5. Copy your existing Cloudflare email and password (found in the old file ```/usr/local/directadmin/scripts/custom/dns_write_post.sh```) and paste into the new dns_write_post.sh ```../dns_write_post.sh```
6. If you are on a recent version and have any domains configured in ```/usr/local/directadmin/scripts/custom/da_cloudflare_dns_sync/domains``` - then copy those files ```cp /usr/local/directadmin/scripts/custom/da_cloudflare_dns_sync/domains/* /home/admin/directadmin_cloudflare_dns/da_cloudflare_dns_sync/domains/```
7. Rename the old script in the da scripts custom folder ```mv /usr/local/directadmin/scripts/custom/da_cloudflare_dns_sync/ /usr/local/directadmin/scripts/custom/previous_version_da_cloudflare_dns_sync/```
8. Rename the old dns_write_post.sh ```mv /usr/local/directadmin/scripts/custom/dns_write_post.sh /usr/local/directadmin/scripts/custom/previous_dns_write_post.sh
9. sudo cp -r /home/admin/directadmin_cloudflare_dns/* /usr/local/directadmin/scripts/custom/
10. Test that everything is running. If so remove the old folder moved in step 7. ```rm -rf /usr/local/directadmin/scripts/custom/previous_version_da_cloudflare_dns_sync/``` and remove the old dns_write_post.sh ```rm /usr/local/directadmin/scripts/custom/previous_dns_write_post.sh```

Sorry that it's not easy.  I'm currently working on turning this into a DirectAdmin plugin, which would make life so much easier and updates automatic, but I need some more time...
