### ISSUE TITLE
Warning: Undefined array key 1 

### ISSUE THREAD

**Issue by Peps03** [pjjonesnz/directadmin_cloudflare_dns#6]
See:

![image](https://user-images.githubusercontent.com/43871548/151573026-6d7f48cf-bb31-4812-bcee-7c4d7f79a026.png)

**Comment by pjjonesnz** [comment]
Hi  
Thanks for your message.

Are you able to let me know what version of PHP is the main version on your server?  I haven't seen this before, but wonder if that is the issue.

Is the software working for you, or are you just letting me know that this error is visible?

Thanks
Paul

**Comment by Peps03** [comment]
Sorry for my late reply. Didn't have time for further testing until now. 

I have a questions / concern. Would it be possible to make the tool 2 way sync? So also fetch changes from CF and update the local DNS records in DA. For a few reasons. All the DNS is now managed at CF. If we have to manually import all records for each domain and all our users we'd be busy forever. Second, we mostly manage DNS for our users and would prefer to keep doing so in CF. So maybe a nightly cron-job could update the local records with changes from CF? And of course on manual sync.

My first tests look promising! It all works well from Da to CF. Nice work!

To answer your question, set PHP versions:

![image](https://user-images.githubusercontent.com/43871548/153211613-29afa6a6-208d-4dce-9cf5-5ad827f4acf5.png)

**Comment by alroberts** [comment]
@pjjonesnz 

I also have this issue. Version: 0.11.6b - Freshly downloaded today.

It's a new server deployment with the following:

- Ubuntu 22.04
- PHP 8.1 (standard with Ubuntu 22.04)
- MariaDB 10.6

I also experience the following errors when testing an API Key:
`Deprecated: http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /usr/local/directadmin/plugins/daflare/vendor/guzzlehttp/guzzle/src/Client.php on line 445`

From what I can see, everything saves fine. Seems likely to be an issue with PHP 8.1, as my other DA server is running 7.4 as it's default and Ubuntu 20.04, MariaDB 10.5, and I don't have the issue there.

**Comment by alroberts** [comment]
@pjjonesnz  - In addition, I cannot use DaFlare on this install either.

`Script output: /usr/local/directadmin/scripts/custom/dns_write_post.sh

Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in /usr/local/directadmin/plugins/daflare/main/Config.php on line 217

Deprecated: Return type of Daflare\Bind\BindReader::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/local/directadmin/plugins/daflare/main/Bind/BindReader.php on line 34

Deprecated: Return type of Daflare\Bind\BindReader::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/local/directadmin/plugins/daflare/main/Bind/BindReader.php on line 42

Deprecated: Return type of Daflare\Bind\BindReader::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/local/directadmin/plugins/daflare/main/Bind/BindReader.php on line 38

Deprecated: Return type of Daflare\Bind\BindReader::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/local/directadmin/plugins/daflare/main/Bind/BindReader.php on line 46

Deprecated: Return type of Daflare\Bind\BindReader::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/local/directadmin/plugins/daflare/main/Bind/BindReader.php on line 30
sh: line 1: /usr/sbin/named-checkzone: No such file or directory




----------  daflare Plugin Output  ----------



Error reading zone file for domain - you may have an error in your zone file.  If this happens for all domains, try switching 'Direct Zone File Access' to 'None' in admin settings.`

Of course, I tried the recommendation, but it still failed.

**Comment by alroberts** [comment]
Is this project abandoned? If so.. I really need to know, because I will have to change everything. Even removing Daflare stopped certain domain actions from completing successfully. It's like it left some configurations behind.

@pjjonesnz

**Comment by Peps03** [comment]
If true, it would be a waste, as it has great potential! Especially if 2-way sync would be added..

**Comment by pjjonesnz** [comment]
Hi Guys. Sorry for my lack of response - it has been a busy, busy year.  I am planning to set some time aside to look at this shortly and get it up to date again.

**Comment by alroberts** [comment]
@pjjonesnz  Thanks buddy! I literally have a server that's running PHP 7.4 which of course is now dead. It represents a bit of a security concern for me.

Any news on updates here? I see that DA are planning to integrate Cloudflare sync at some point, but I'm pretty used to how this works.

**Comment by pjjonesnz** [comment]
It has been a long time coming...
[daflare v0.14.0b](https://daflare.com/knowledge-base/changelog/)
